### ISSUE TITLE
"No new notifications! Skipping" permanently

### ISSUE THREAD

**Issue by bullik01** [azhuge233/UbisoftGiveawayNotifier#3]
Hi! I get "No new notifications! Skipping" permanently and don't get any notifications.
And thats all :(

![image](https://github.com/azhuge233/UbisoftGiveawayNotifier/assets/4389593/55c4b04a-0e02-4e0e-8822-c4cbf4ce2a91)

**Comment by bullik01** [comment]
But at that moment ubisoft have few fribies

**Comment by azhuge233** [comment]
Only enties have "Game giveaway" span on the top left corner is counted as a giveaway (or freebie) in this project (look at [ParseString.cs](https://github.com/azhuge233/UbisoftGiveawayNotifier/blob/ef713f950b32e925f73c070723c5f97f2aed3897/UbisoftGiveawayNotifier/Strings/ParseString.cs#L16C2-L16C2) and [Parser.cs](https://github.com/azhuge233/UbisoftGiveawayNotifier/blob/ef713f950b32e925f73c070723c5f97f2aed3897/UbisoftGiveawayNotifier/Services/Parser.cs#L33)), others like "FREE WEEK-END" or "FREE TO PLAY" is not counted, that's why it always shows `No new notifications! Skipping`.

Compare the content on [this web archive](http://web.archive.org/web/20220526042010/https://free.ubisoft.com/) with current [https://free.ubisoft.com/](https://free.ubisoft.com) and you will get it.

AFAIK, Ubisoft's latest giveaway listed on [https://free.ubisoft.com/](https://free.ubisoft.com) was Roller Champions, which is on May/25/2022 (over a year ago), they don't update this page that much (at leatest for giveaways).

Also, there are log files under [publish directory]/log, check that for more debug output for technical issues.

**Comment by bullik01** [comment]
Thanks for detailed reply!
In log probably all good: https://paste.feed-the-beast.com/view/9fea5711

**Comment by azhuge233** [comment]
Yes the log is fine, I'm having the same log for a long time.
